const resList = [
    {
          type: "F",
          id: "418859",
          name: "Udupi Shanthi Sagar",
          uuid: "c581c198-95b7-47ff-8768-dc5573d01d67",
          city: "1",
          area: "Frazer Town",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "rlfcmogwwbrgi1xa4owk",
          cuisines: ["South Indian", "Beverages"],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 27,
          slugs: {
            restaurant: "udupi-shanthi-sagar-frazer-town-frazer-town",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "8, Coles Rd, Cleveland Town, Pulikeshi Nagar, Bengaluru, Karnataka 560005, India",
          locality: "Cleveland Town",
          parentId: 233016,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          longDistanceEnabled: 1,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          lastMileTravelString: "4.4 kms",
          hasSurge: false,
          avgRating: "3.4",
          totalRatings: 1000,
          new: false,
    },
    {
          type: "F",
          id: "58197",
          name: "Shanti Sagar",
          uuid: "c53b677e-5442-4fb8-b237-b9619a42ad36",
          city: "1",
          area: "Ulsoor",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ddlewhiegjaigcxnp5tr",
          cuisines: ["South Indian", "North Indian", "Chinese"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 26,
          slugs: {
            restaurant: "shanti-sagar-ulsoor-central-bangalore",
            city: "bangalore",
          },
          cityState: "1",
          address: "9/1, Tank Road, Ulsoor, near lake, bangalore-560042",
          locality: "Tank Road",
          parentId: 20012,
          unserviceable: false,
          veg: false,
          promoted: false,
          avgRating: "4.3",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "210945",
          name: "Royal Restaurant",
          uuid: "9b33bca4-65e6-4a26-af3e-f47c4476ed4d",
          city: "1",
          area: "Shivajinagar",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "yicweopn4lzcjlqy4jvq",
          cuisines: ["Chinese", "North Indian", "Tandoor"],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 26,
          slugs: {
            restaurant: "royal-restaurant-central-bangalore-central-bangalore",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "Broadway Road Police Station, HKP Road, Sulthangunta, Shivajinagar, Bengaluru, Bangalore Urban, Karnataka, India",
          locality: "Sulthangunta",
          parentId: 2896,
          avgRating: "3.9",
          totalRatings: 5000,
          new: false,
    },
    {
          type: "F",
          id: "23681",
          name: "McDonald's",
          uuid: "1b86411f-a176-452f-b4f1-869c8c817c3c",
          city: "1",
          area: "Indiranagar",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
          cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 43,
          cityState: "1",
          address:
            "Door No 539, Ashwini Complex,Indiranagar, CMH Road,Bengaluru- 38",
          locality: "Cmh Road",
          parentId: 630,
          unserviceable: false,
          veg: false,
          longDistanceEnabled: 0,
          avgRating: "3.4",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "602668",
          name: "UDUPI PARK IN",
          uuid: "857e66cf-62fc-4a0d-bf81-3e09a695bef1",
          city: "1",
          area: "Hebbal",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "dds1aswgv4r7ysciuhef",
          cuisines: ["Beverages", "Indian", "Fast Food"],
          tags: [],
          costForTwo: 7000,
          costForTwoString: "₹70 FOR TWO",
          deliveryTime: 33,
          cityState: "1",
          address:
            "SHOP NO.29, UDUPI PARK IN HOTEL, GVR PLAZA, NEAR CANARA BANK, HEBBAL, BANGALORE, Hebbala , B.B.M.P North, Karnataka-560024",
          locality: "Vinayakanagar",
          parentId: 359397,
          unserviceable: false,
          veg: false,
          avgRating: "4.0",
          totalRatings: 100,
          new: false,
    },
    {
          type: "F",
          id: "476261",
          name: "SRI NAYVEDYA VEG",
          uuid: "99127847-7b37-4504-a701-5cd1b8e119f7",
          city: "1",
          area: "Jayanagar",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "hljbvcwexdml5cllguis",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 27,
          slugs: {
            restaurant: "sri-nayvedya-veg-jayanagar-jayanagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "42 ( Old No. 143, 6th C Main Road, 4th Block, Jayanagar, Bengaluru, Karnataka 560041, India",
          locality: "4th Block",
          parentId: 285843,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "4.3",
          totalRatings: 500,
          new: false,
    },
    {
          type: "F",
          id: "210099",
          name: "Amma Pastries",
          uuid: "80c7293c-c01f-4c72-8829-d32b2e541715",
          city: "1",
          area: "Nagarbhavi",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "vztt7igsrtqvoxcfgwzx",
          cuisines: ["Desserts", "Indian", "Snacks", "Sweets"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 37,
          slugs: {
            restaurant: "holige-mane-brahmins-bakery-basavanagudi-basavanagudi",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "39 opp reliance fresh moodalapalya circle nagara bhavi main road Bengaluru",
          locality: "Mudalapalya Circle",
          parentId: 388842,
          unserviceable: false,
          veg: false,
          lastMileTravelString: "8.6 kms",
          hasSurge: false,
          promoted: false,
          avgRating: "3.9",
          totalRatings: 5000,
          new: false,
    },
    {
          type: "F",
          id: "96527",
          name: "Vijayalakshmi",
          uuid: "832cd579-956f-4480-8cf8-42af4fea46a0",
          city: "1",
          area: "Basavanagudi",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "r94u50lcikbaqulaofdi",
          cuisines: ["South Indian", "North Indian", "Chinese"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 29,
          slugs: {
            restaurant: "vijayalakshmi-basavanagudi",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "#37, SHREE COMPLEX, next to dominos pizza, Bull Temple Road, Basavanagudi, Bangalore-560004",
          locality: "Bull Temple Rd",
          parentId: 20982,
          unserviceable: false,
          veg: true,
          avgRating: "4.1",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "15895",
          name: "South Idlis",
          uuid: "eed71145-a0dd-4cf8-8465-7977572c940c",
          city: "1",
          area: "Rajajinagar",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ttp1jprgfa5pmiydspna",
          cuisines: ["South Indian", "Chinese"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 34,
          slugs: {
            restaurant: "south-idlis-rajajinagar-rajajinagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "#12294/A, Tank Bund Road, 17th Cross, Rajajinagar, 2nd Stage, Bangalore-10",
          locality: "Tank Bund Road",
          parentId: 21535,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "3.0",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "16197",
          name: "Kullad Cafe",
          uuid: "c22c7015-19e0-4379-b281-fc21642ec4b2",
          city: "1",
          area: "BTM Layout",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "jazqpngjksacolwpa4gb",
          cuisines: ["North Indian", "Fast Food", "Snacks", "Beverages"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 52,
          slugs: {
            restaurant: "kullad-cafe-btm-btm",
            city: "bangalore",
          },
          cityState: "1",
          address: "16th Main, BTM Layout, 2nd Stage, Near Udupi Signal.",
          locality: "2nd Stage",
          parentId: 21550,
          unserviceable: false,
          veg: false,
          avgRating: "4.0",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "30458",
          name: "Sukh Sagar",
          uuid: "76fe34b7-fc63-4c49-ac54-425f9e985b48",
          city: "1",
          area: "Koramangala",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ztykpc9tijg8znovvbzx",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 31,
          slugs: {
            restaurant: "sukh-sagar-koramangala-5th-block-koramangala",
            city: "bangalore",
          },
          cityState: "1",
          address: "no 62. 17th A MAIN 5TH A BLOCK KORAMANGALA 560095",
          locality: "5th A Block",
          parentId: 3115,
          unserviceable: false,
          veg: true,
          avgRating: "3.3",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "297530",
          name: "KRISHNA VAIBHAVA",
          uuid: "5816e153-8181-4282-b7e3-6f167d92a0e7",
          city: "1",
          area: "Vijayanagar",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "dpnjzshuy4ots4hjil3t",
          cuisines: ["Indian", "Chinese"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 36,
          slugs: {
            restaurant: "krishna-vaibhava-vijayanagar-vijayanagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "NO 1712, 17TH CROSS , 21ST MAIN , BEHIND MARUTHI MANDIR, CHORD ROAD EXTENTION, VIJAYANAGAR BENGALURU,560040",
          locality: "Chord Road",
          parentId: 21125,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "4.3",
          totalRatings: 5000,
          new: false,
    },
    {
          type: "F",
          id: "85320",
          name: "By 2 Coffee",
          uuid: "3690f65a-e228-43f9-9ead-6906a9cf1744",
          city: "1",
          area: "Chamarajpet",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "pzyccoxkjhlvwtiv5hsq",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 10000,
          costForTwoString: "₹100 FOR TWO",
          deliveryTime: 26,
          slugs: {
            restaurant: "by-2-coffee-basavanagudi-basavanagudi",
            city: "bangalore",
          },
          cityState: "1",
          address: "Shop 69, 6th Main Road, Appurao Road, Chamarajpet, Bangalore",
          locality: "Chamrajpet",
          parentId: 172,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "4.5",
          totalRatings: 1000,
          new: false,
    },
    {
          type: "F",
          id: "145076",
          name: "Halli Jonne Biriyani",
          uuid: "818bd70e-3640-4739-85ea-e79d4c333c75",
          city: "1",
          area: "Jayanagar",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "hukiflnai1hosydergnx",
          cuisines: ["South Indian", "Biryani"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 34,
          slugs: {
            restaurant: "halli-jonne-biriyani-jayanagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "44, 4, 13th Main Rd, Opp BHS College, 4th T Block East, KV Layout, Jayanagar, Bengaluru, Karnataka 560011",
          locality: "4th T Block",
          parentId: 21321,
          unserviceable: false,
          veg: false,
          promoted: false,
          avgRating: "4.3",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "111261",
          name: "Brahmin's Coffee Bar",
          uuid: "2f0b8fd5-06e7-40c2-b99b-2531418c2a7b",
          city: "1",
          area: "Basavanagudi",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ao84kwgogd5oicnh4dpv",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 10000,
          costForTwoString: "₹100 FOR TWO",
          deliveryTime: 28,
          slugs: {
            restaurant: "brahmin39s-coffee-bar-basavanagudi",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "Ranga Rao Road  Near Shankar Mutt  Shankarapura  Near Basavanagudi  Bangalore",
          locality: "Shankarapura",
          parentId: 20978,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "4.7",
          totalRatings: 10000,
          new: false,
    },
    {
          type: "F",
          id: "110506",
          name: "Nammura Upachara",
          uuid: "828754eb-bc2f-4b3b-a3cb-7843eb7e3bf8",
          city: "1",
          area: "Rajajinagar",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "vgh0d1sn9whx77ry8i2i",
          cuisines: ["South Indian", "Chinese", "North Indian"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 32,
          slugs: {
            restaurant: "nammura-upachara-rajajinagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "51 , lic moddel colony west of courd road, Basaweshwarnagara, Banglore 79",
          locality: "West Of Chord Road",
          parentId: 143726,
          unserviceable: false,
          veg: true,
          promoted: false,
          avgRating: "4.3",
          totalRatings: 1000,
          new: false,
    },
  ];

  export default resList;